### ISSUE TITLE
No such file or directory @ rb_sysopen - foundation (Errno::ENOENT)

### ISSUE THREAD

**Issue by okanck** [MobiVM/robovm-bro-gen#2]
I got "No such file or directory @ rb_sysopen - foundation (Errno::ENOENT)" error after I run the command below:

Input:
`~/Developer/robovm-bro-gen/bro-gen.rb ../java facebook-loginkit.yaml`

Output:
```
Using libclang: /Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
Clang version detected: [11, 0]
Processing facebook-loginkit.yaml...
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/psych.rb:474:in `initialize': No such file or directory @ rb_sysopen - foundation (Errno::ENOENT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /Users/okanck/Developer/robovm-bro-gen/bro-gen.rb:2898:in `block (2 levels) in <main>'
	from /Users/okanck/Developer/robovm-bro-gen/bro-gen.rb:2883:in `each'
	from /Users/okanck/Developer/robovm-bro-gen/bro-gen.rb:2883:in `block in <main>'
	from /Users/okanck/Developer/robovm-bro-gen/bro-gen.rb:2835:in `each'
	from /Users/okanck/Developer/robovm-bro-gen/bro-gen.rb:2835:in `<main>'
```

Edit:
OS: Mac Mojave 10.14.6 (18G2022) 
XCode: Version 11.3 (11C29)

`ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]`

**Comment by dkimitsa** [comment]
please check [tutorial](https://dkimitsa.github.io/2017/10/19/bro-gen-tutorial/) and pay attention where what repositories are required and how they should be located to each other. 
you need RoboVM sources to be properly located next to bro-gen
